export function parseBinance(text) {}
export function parseBybit(text) {}
export function parseCexio(text) {}
export function parseCoinmarketcap(text) {}
export function parseCoinCap(text) {}
export function parseCoinCodex(text) {}
export function parseCoingecko(text) {}
export function parseCoinlore(text) {}
export function parseCryptocompare(text) {}
export function parseHuobi(text) {}
export function parseKucoin(text) {}
export function parsePricemessari(text) {}
export function parsePricepaprika(text) {}
export function parseSwapzone(text) {}
